[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install asgiref==3.9.1 Django==5.2.6 django-environ==0.12.0 djangorestframework==3.16.1 gunicorn==23.0.0 packaging==25.0 psycopg2-binary==2.9.10 sqlparse==0.5.3 tzdata==2025.2"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmds = [
  ". /opt/venv/bin/activate",
  "cp .env .env.build",  # Copia el archivo .env para el build
  "set -a && . .env.build && set +a",  # Carga las variables de entorno
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]